export const categories = {
  "Explicit Nudity": "Explicit Nudity",
  Nudity: "Nudity",
  "Graphic Male Nudity": "Graphic Male Nudity",
  "Graphic Female Nudity": "Graphic Female Nudity",
  "Sexual Activity": "Sexual Activity",
  "Illustrated Explicit Nudity": "Illustrated Explicit Nudity",
  "Adult Toys": "Adult Toys",
  Suggestive: "Suggestive",
  "Female Swimwear Or Underwear": "Female Swimwear Or Underwear",
  "Male Swimwear Or Underwear": "Male Swimwear Or Underwear",
  "Partial Nudity": "Partial Nudity",
  "Barechested Male": "Barechested Male",
  "Revealing Clothes": "Revealing Clothes",
  "Sexual Situations": "Sexual Situations",
  Violence: "Violence",
  "Graphic Violence Or Gore": "Graphic Violence Or Gore",
  "Physical Violence": "Physical Violence",
  "Weapon Violence": "Weapon Violence",
  Weapons: "Weapons",
  "Self Injury": "Self Injury",
  "Visually Disturbing": "Visually Disturbing",
  "Emaciated Bodies": "Emaciated Bodies",
  Corpses: "Corpses",
  Hanging: "Hanging",
  "Air Crash": "Air Crash",
  "Explosions And Blasts": "Explosions And Blasts",
  "Rude Gestures": "Rude Gestures",
  "Middle Finger": "Middle Finger",
  Drugs: "Drugs",
  "Drug Products": "Drug Products",
  "Drug Use": "Drug Use",
  Pills: "Pills",
  "Drug Paraphernalia": "Drug Paraphernalia",
  Tobacco: "Tobacco",
  "Tobacco Products": "Tobacco Products",
  Smoking: "Smoking",
  Alcohol: "Alcohol",
  Drinking: "Drinking",
  "Alcoholic Beverages": "Alcoholic Beverages",
  Gambling: "Gambling",
  "Hate Symbols": "Hate Symbols",
  "Nazi Party": "Nazi Party",
  "White Supremacy": "White Supremacy",
  Extremist: "Extremist",
};
